name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
      
    - name: Get next version
      uses: reecetech/version-increment@2023.9.3
      id: version
      with:
        scheme: semver
        increment: patch
        
    - run: git tag ${{ steps.version.outputs.version }}
    - run: git push origin ${{ steps.version.outputs.version }}    
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
   

    - name: Build and push BlazorPocketApp
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: blazordevlab/blazorpocketapp:${{ steps.version.outputs.version }}

    - name: Build and push BlazorPocketApp with latest tag
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: blazordevlab/blazorpocketapp:latest


    - name: Build and push BlazorPocketBase
      uses: docker/build-push-action@v5
      with:
        context: ./pocketbase
        file: ./pocketbase/Dockerfile
        push: true
        tags: blazordevlab/blazorpocketbase:${{ steps.version.outputs.version }}
        
    - name: Build and push BlazorPocketBase with latest tag
      uses: docker/build-push-action@v5
      with:
        context: ./pocketbase
        file: ./pocketbase/Dockerfile
        push: true
        tags: blazordevlab/blazorpocketbase:latest
     
